### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by ifloppy** [GaleMC/Gale#3]
Server crashed while starting the server, but it works well with Purpur
Build:https://github.com/GaleMC/Gale/actions/runs/4107567955
Crash report:
[crash-2023-02-07_23.13.39-server.txt](https://github.com/GaleMC/Gale/files/10676776/crash-2023-02-07_23.13.39-server.txt)

btw，something wrong with some plugins(https://www.spigotmc.org/resources/%E2%9C%85-infinite-parkour-%E2%96%B6-randomly-generating-parkour-rewards-mysql-leaderboard-spectate-others.87226/), two things seem to be related
```[23:18:27] [Server thread/ERROR]: Error occurred while enabling IP v4.0.4 (Is it up to date?)
java.lang.NullPointerException: Cannot assign field "serverLevelArrayIndex" because "this.levelArray[i]" is null
	at net.minecraft.server.MinecraftServer.removeLevel(MinecraftServer.java:1821) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.unloadWorld(CraftServer.java:1353) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.unloadWorld(CraftServer.java:1308) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorldFromBukkit(WorldManager.java:587) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorld(WorldManager.java:388) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorld(WorldManager.java:378) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.deleteWorld(WorldManager.java:535) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.deleteWorld(WorldManager.java:567) ~[Multiverse-Core-4.3.1.jar:?]
	at dev.efnilite.ip.hook.MultiverseHook.deleteWorld(MultiverseHook.java:38) ~[IP-4.0.4.jar:?]
	at dev.efnilite.ip.world.WorldHandler.deleteWorld(WorldHandler.java:79) ~[IP-4.0.4.jar:?]
	at dev.efnilite.ip.world.WorldHandler.createWorld(WorldHandler.java:37) ~[IP-4.0.4.jar:?]
	at dev.efnilite.ip.IP.enable(IP.java:166) ~[IP-4.0.4.jar:?]
	at dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:58) ~[vilib-1.1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:584) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:498) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:734) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:533) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:415) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:18:27] [Server thread/INFO]: [IP] Disabling IP v4.0.4
[23:18:27] [Server thread/ERROR]: [IP] ##
[23:18:27] [Server thread/ERROR]: [IP] ## IP has encountered a critical error!
[23:18:27] [Server thread/ERROR]: [IP] ## World is null
[23:18:27] [Server thread/ERROR]: [IP] ##
[23:18:27] [Server thread/ERROR]: [IP] ## No stack trace provided
[23:18:27] [Server thread/ERROR]: [IP] ##
[23:18:27] [Server thread/ERROR]: [IP] ## This is probably not your fault, but you may be able to fix it.
[23:18:27] [Server thread/ERROR]: [IP] ## You should try: delete the parkour world folder and restart the server
[23:18:27] [Server thread/ERROR]: [IP] ## Contact the developer if this doesn't work.
[23:18:27] [Server thread/ERROR]: [IP] ## Be sure to send the entire error while reporting.
[23:18:27] [Server thread/ERROR]: [IP] ##
[23:18:27] [Server thread/ERROR]: [IP] ## Version information:
[23:18:27] [Server thread/ERROR]: [IP] ##	Plugin Version: 4.0.4
[23:18:27] [Server thread/ERROR]: [IP] ##	vilib Version: 1.1.0
[23:18:27] [Server thread/ERROR]: [IP] ##	Minecraft: V1.19
[23:18:27] [Server thread/ERROR]: [IP] ##```
```[23:18:28] [Server thread/ERROR]: Error occurred while disabling IP v4.0.4 (Is it up to date?)
java.lang.NullPointerException: Cannot assign field "serverLevelArrayIndex" because "this.levelArray[i]" is null
	at net.minecraft.server.MinecraftServer.removeLevel(MinecraftServer.java:1821) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.unloadWorld(CraftServer.java:1353) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.unloadWorld(CraftServer.java:1308) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorldFromBukkit(WorldManager.java:587) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorld(WorldManager.java:388) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.unloadWorld(WorldManager.java:378) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.deleteWorld(WorldManager.java:535) ~[Multiverse-Core-4.3.1.jar:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.deleteWorld(WorldManager.java:567) ~[Multiverse-Core-4.3.1.jar:?]
	at dev.efnilite.ip.hook.MultiverseHook.deleteWorld(MultiverseHook.java:38) ~[IP-4.0.4.jar:?]
	at dev.efnilite.ip.world.WorldHandler.deleteWorld(WorldHandler.java:79) ~[IP-4.0.4.jar:?]
	at dev.efnilite.ip.IP.disable(IP.java:218) ~[IP-4.0.4.jar:?]
	at dev.efnilite.vilib.ViPlugin.onDisable(ViPlugin.java:63) ~[vilib-1.1.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:400) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:581) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:375) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[gale-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:584) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:498) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:734) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:533) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:415) ~[gale-1.19.3.jar:git-Gale-"ac4ce86"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by MartijnMuijsers** [comment]
It should be fixed in the newest build:
https://github.com/GaleMC/Gale/actions/runs/4117883643

Could you let me know if it's fixed for you?

**Comment by ifloppy** [comment]
> It should be fixed in the newest build: https://github.com/GaleMC/Gale/actions/runs/4117883643
> 
> Could you let me know if it's fixed for you?

Problem solved. Thanks a lot!
